//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "abilities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(unique)]
    pub identifier: String,
    pub generation_id: i32,
    pub is_main_series: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ability_flavor_text::Entity")]
    AbilityFlavorText,
    #[sea_orm(has_many = "super::ability_names::Entity")]
    AbilityNames,
    #[sea_orm(
        belongs_to = "super::generations::Entity",
        from = "Column::GenerationId",
        to = "super::generations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Generations,
    #[sea_orm(has_many = "super::pokemon_abilities::Entity")]
    PokemonAbilities,
}

impl Related<super::ability_flavor_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AbilityFlavorText.def()
    }
}

impl Related<super::ability_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AbilityNames.def()
    }
}

impl Related<super::generations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Generations.def()
    }
}

impl Related<super::pokemon_abilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonAbilities.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::ability_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ability_names::Relation::Abilities.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
