//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "egg_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pokemon_egg_groups::Entity")]
    PokemonEggGroups,
}

impl Related<super::pokemon_egg_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonEggGroups.def()
    }
}

impl Related<super::pokemon_species::Entity> for Entity {
    fn to() -> RelationDef {
        super::pokemon_egg_groups::Relation::PokemonSpecies.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::pokemon_egg_groups::Relation::EggGroups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
