//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "encounter_methods")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub identifier: String,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::encounter_slots::Entity")]
    EncounterSlots,
    #[sea_orm(has_many = "super::location_area_encounter_rates::Entity")]
    LocationAreaEncounterRates,
}

impl Related<super::encounter_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncounterSlots.def()
    }
}

impl Related<super::location_area_encounter_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationAreaEncounterRates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
