//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "encounter_slots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub version_group_id: i32,
    pub encounter_method_id: i32,
    pub slot: Option<i32>,
    pub rarity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encounter_methods::Entity",
        from = "Column::EncounterMethodId",
        to = "super::encounter_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EncounterMethods,
    #[sea_orm(has_many = "super::encounters::Entity")]
    Encounters,
}

impl Related<super::encounter_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncounterMethods.def()
    }
}

impl Related<super::encounters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Encounters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
