//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "generations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub main_region_id: i32,
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::abilities::Entity")]
    Abilities,
    #[sea_orm(has_many = "super::generation_names::Entity")]
    GenerationNames,
    #[sea_orm(has_many = "super::moves::Entity")]
    Moves,
    #[sea_orm(has_many = "super::pokemon_species::Entity")]
    PokemonSpecies,
    #[sea_orm(has_many = "super::types::Entity")]
    Types,
    #[sea_orm(has_many = "super::version_groups::Entity")]
    VersionGroups,
}

impl Related<super::abilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Abilities.def()
    }
}

impl Related<super::generation_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GenerationNames.def()
    }
}

impl Related<super::moves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Moves.def()
    }
}

impl Related<super::pokemon_species::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonSpecies.def()
    }
}

impl Related<super::types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Types.def()
    }
}

impl Related<super::version_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionGroups.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::generation_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::generation_names::Relation::Generations.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
