//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "item_pockets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(unique)]
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::item_categories::Entity")]
    ItemCategories,
    #[sea_orm(has_many = "super::item_pocket_names::Entity")]
    ItemPocketNames,
}

impl Related<super::item_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemCategories.def()
    }
}

impl Related<super::item_pocket_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemPocketNames.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::item_pocket_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::item_pocket_names::Relation::ItemPockets.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
