//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "item_pocket_names")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_pocket_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub local_language_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_pockets::Entity",
        from = "Column::ItemPocketId",
        to = "super::item_pockets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPockets,
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LocalLanguageId",
        to = "super::languages::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Languages,
}

impl Related<super::item_pockets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemPockets.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
