//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "item_categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub pocket_id: i32,
    #[sea_orm(unique)]
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_pockets::Entity",
        from = "Column::PocketId",
        to = "super::item_pockets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemPockets,
    #[sea_orm(has_many = "super::items::Entity")]
    Items,
}

impl Related<super::item_pockets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemPockets.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
