//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "location_area_encounter_rates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub location_area_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub encounter_method_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version_id: i32,
    pub rate: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encounter_methods::Entity",
        from = "Column::EncounterMethodId",
        to = "super::encounter_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EncounterMethods,
    #[sea_orm(
        belongs_to = "super::location_areas::Entity",
        from = "Column::LocationAreaId",
        to = "super::location_areas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LocationAreas,
    #[sea_orm(
        belongs_to = "super::versions::Entity",
        from = "Column::VersionId",
        to = "super::versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Versions,
}

impl Related<super::encounter_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncounterMethods.def()
    }
}

impl Related<super::location_areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationAreas.def()
    }
}

impl Related<super::versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Versions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
