//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "locations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub region_id: Option<i32>,
    #[sea_orm(unique)]
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::location_areas::Entity")]
    LocationAreas,
    #[sea_orm(has_many = "super::location_names::Entity")]
    LocationNames,
    #[sea_orm(has_many = "super::pokemon_evolution::Entity")]
    PokemonEvolution,
    #[sea_orm(
        belongs_to = "super::regions::Entity",
        from = "Column::RegionId",
        to = "super::regions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Regions,
}

impl Related<super::location_areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationAreas.def()
    }
}

impl Related<super::location_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationNames.def()
    }
}

impl Related<super::pokemon_evolution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonEvolution.def()
    }
}

impl Related<super::regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Regions.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::location_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::location_names::Relation::Locations.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
