//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pokemon_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stat_id: i32,
    pub base_stat: i32,
    pub effort: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pokemon::Entity",
        from = "Column::PokemonId",
        to = "super::pokemon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pokemon,
    #[sea_orm(
        belongs_to = "super::stats::Entity",
        from = "Column::StatId",
        to = "super::stats::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stats,
}

impl Related<super::pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pokemon.def()
    }
}

impl Related<super::stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
