//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_egg_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub species_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub egg_group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::egg_groups::Entity",
        from = "Column::EggGroupId",
        to = "super::egg_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EggGroups,
    #[sea_orm(
        belongs_to = "super::pokemon_species::Entity",
        from = "Column::SpeciesId",
        to = "super::pokemon_species::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonSpecies,
}

impl Related<super::egg_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EggGroups.def()
    }
}

impl Related<super::pokemon_species::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonSpecies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
