//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_colors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pokemon_color_names::Entity")]
    PokemonColorNames,
    #[sea_orm(has_many = "super::pokemon_species::Entity")]
    PokemonSpecies,
}

impl Related<super::pokemon_color_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonColorNames.def()
    }
}

impl Related<super::pokemon_species::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonSpecies.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::pokemon_color_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::pokemon_color_names::Relation::PokemonColors
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
