//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pokemon_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub type_id: i32,
    pub slot: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pokemon::Entity",
        from = "Column::PokemonId",
        to = "super::pokemon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pokemon,
    #[sea_orm(
        belongs_to = "super::types::Entity",
        from = "Column::TypeId",
        to = "super::types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Types,
}

impl Related<super::pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pokemon.def()
    }
}

impl Related<super::types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Types.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
