//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokedexes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub region_id: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub identifier: String,
    pub is_main_series: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pokedex_version_groups::Entity")]
    PokedexVersionGroups,
    #[sea_orm(
        belongs_to = "super::regions::Entity",
        from = "Column::RegionId",
        to = "super::regions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Regions,
}

impl Related<super::pokedex_version_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokedexVersionGroups.def()
    }
}

impl Related<super::regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Regions.def()
    }
}

impl Related<super::version_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::pokedex_version_groups::Relation::VersionGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::pokedex_version_groups::Relation::Pokedexes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
