//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_moves")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pokemon_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version_group_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub move_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pokemon_move_method_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub level: i32,
    pub order: Option<i32>,
    pub mastery: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::moves::Entity",
        from = "Column::MoveId",
        to = "super::moves::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Moves,
    #[sea_orm(
        belongs_to = "super::pokemon::Entity",
        from = "Column::PokemonId",
        to = "super::pokemon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pokemon,
    #[sea_orm(
        belongs_to = "super::pokemon_move_methods::Entity",
        from = "Column::PokemonMoveMethodId",
        to = "super::pokemon_move_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonMoveMethods,
    #[sea_orm(
        belongs_to = "super::version_groups::Entity",
        from = "Column::VersionGroupId",
        to = "super::version_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    VersionGroups,
}

impl Related<super::moves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Moves.def()
    }
}

impl Related<super::pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pokemon.def()
    }
}

impl Related<super::pokemon_move_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonMoveMethods.def()
    }
}

impl Related<super::version_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
