//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "regions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(unique)]
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::locations::Entity")]
    Locations,
    #[sea_orm(has_many = "super::pokedexes::Entity")]
    Pokedexes,
    #[sea_orm(has_many = "super::region_names::Entity")]
    RegionNames,
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Locations.def()
    }
}

impl Related<super::pokedexes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pokedexes.def()
    }
}

impl Related<super::region_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegionNames.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::region_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::region_names::Relation::Regions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
