//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub version_group_id: i32,
    #[sea_orm(unique)]
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::encounters::Entity")]
    Encounters,
    #[sea_orm(has_many = "super::location_area_encounter_rates::Entity")]
    LocationAreaEncounterRates,
    #[sea_orm(has_many = "super::pokemon_species_flavor_text::Entity")]
    PokemonSpeciesFlavorText,
    #[sea_orm(
        belongs_to = "super::version_groups::Entity",
        from = "Column::VersionGroupId",
        to = "super::version_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    VersionGroups,
    #[sea_orm(has_many = "super::version_names::Entity")]
    VersionNames,
}

impl Related<super::encounters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Encounters.def()
    }
}

impl Related<super::location_area_encounter_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationAreaEncounterRates.def()
    }
}

impl Related<super::pokemon_species_flavor_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonSpeciesFlavorText.def()
    }
}

impl Related<super::version_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionGroups.def()
    }
}

impl Related<super::version_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionNames.def()
    }
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        super::version_names::Relation::Languages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::version_names::Relation::Versions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
