//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "pokemon_species_flavor_text")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub species_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub language_id: i32,
    #[sea_orm(column_type = "Text")]
    pub flavor_text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::languages::Entity",
        from = "Column::LanguageId",
        to = "super::languages::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Languages,
    #[sea_orm(
        belongs_to = "super::pokemon_species::Entity",
        from = "Column::SpeciesId",
        to = "super::pokemon_species::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonSpecies,
    #[sea_orm(
        belongs_to = "super::versions::Entity",
        from = "Column::VersionId",
        to = "super::versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Versions,
}

impl Related<super::languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Languages.def()
    }
}

impl Related<super::pokemon_species::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonSpecies.def()
    }
}

impl Related<super::versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Versions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
