//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    schemars :: JsonSchema,
    aide :: OperationIo,
)]
#[sea_orm(table_name = "stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub damage_class_id: Option<i32>,
    pub identifier: String,
    pub is_battle_only: bool,
    pub game_index: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pokemon_stats::Entity")]
    PokemonStats,
}

impl Related<super::pokemon_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonStats.def()
    }
}

impl Related<super::pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        super::pokemon_stats::Relation::Pokemon.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::pokemon_stats::Relation::Stats.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
